## Compose file (conflict resolved keeping local configuration)
services:
  # Backend API (if needed)
  onelastai-backend:
    build: ./backend
    container_name: onelastai-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Frontend Application
  onelastai-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: http://onelastai-backend:3000
    container_name: onelastai-frontend
    depends_on:
      - onelastai-backend
    ports:
      - "8080:80"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-devredis123}
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    name: onelastai-net